import { DeviceIdentity, MatchConfidence } from './types';

/**
 * Device matching. Deliberately conservative: per the investigation's own
 * warning (a wrong reference price is worse than a missing one), this
 * module does NOT do semantic fuzzy matching across different model names
 * ("OnePlus 15R" must never match "OnePlus 15", "iPhone 15 Pro" must never
 * match "iPhone 15 Pro Max"). The only thing "fuzzified" here is pure
 * string FORMATTING (case, whitespace, punctuation, GB/gb, "/" vs "-") -
 * anything that differs after that normalization is treated as a different
 * device and reported as unmatched rather than guessed.
 */

/** Collapses formatting differences without touching semantic content:
 * lowercase and strip every non-alphanumeric character (spaces, punctuation,
 * slashes) entirely, so "128 GB" / "128GB" / "128-GB" all normalize
 * identically. This only removes SEPARATORS, never digits or letters, so
 * it cannot merge two different model numbers or variants - "15" and "15r"
 * still normalize to "15" and "15r" respectively. */
export function normalize(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/** The existing lookupKey algorithm used throughout the live pricing path
 * (app/quote/page.tsx, server/modules/quote/service.ts). Reproduced here
 * verbatim (not imported from those files, to avoid this module depending
 * on frontend/server code) so the legacy-format matcher stays byte-for-byte
 * compatible with every existing cashify_prices.json key. */
export function legacyLookupKey(model: string, storage: string): string {
  return `${model}-${storage}`.toLowerCase().replace(/[^a-z0-9]/g, '-');
}

export interface MatchResult {
  confidence: MatchConfidence;
  evidence: string;
}

/**
 * Compares two device identities and reports how confidently they refer to
 * the same physical variant. Never returns a confidence higher than the
 * evidence supports - when in doubt, this returns 'unmatched'.
 */
export function matchDevices(a: DeviceIdentity, b: DeviceIdentity): MatchResult {
  const brandA = normalize(a.brand);
  const brandB = normalize(b.brand);
  const modelA = normalize(a.model);
  const modelB = normalize(b.model);
  const storageA = normalize(a.storage);
  const storageB = normalize(b.storage);

  if (brandA === brandB && modelA === modelB && storageA === storageB) {
    const rawIdentical = a.brand === b.brand && a.model === b.model && a.storage === b.storage;
    return rawIdentical
      ? { confidence: 'exact', evidence: 'identical brand/model/storage strings' }
      : { confidence: 'high', evidence: 'identical after normalizing case/whitespace/punctuation only' };
  }

  if (brandA !== brandB) {
    return { confidence: 'unmatched', evidence: `brand mismatch: "${a.brand}" vs "${b.brand}"` };
  }

  if (modelA !== modelB) {
    // This is the exact trap case Phase 5 warns about - do not attempt to
    // rescue this with substring/fuzzy logic. A model-name difference
    // (e.g. "15" vs "15r", "pro" vs "pro max") means a different product.
    return { confidence: 'unmatched', evidence: `model mismatch after normalization: "${modelA}" vs "${modelB}"` };
  }

  // Same brand + model, different storage string after normalization.
  return { confidence: 'unmatched', evidence: `storage mismatch: "${a.storage}" vs "${b.storage}"` };
}

/**
 * Given a target device and a dictionary of legacy `${model}-${storage}`
 * style keys (the shape of the existing cashify_prices.json files), find
 * the matching entry using the SAME algorithm the live pricing path uses,
 * so migrating this data cannot change which price a device resolves to
 * today. Returns 'exact' confidence only for a literal key hit - this
 * function does not attempt anything fuzzier for legacy data, since the
 * legacy keys were generated by the same deterministic function and a
 * miss just means "no entry", not "ambiguous".
 */
export function findLegacyMatch(
  device: DeviceIdentity,
  legacyPrices: Record<string, number>
): { price: number; matchedKey: string } | null {
  const key = legacyLookupKey(device.model, device.storage);
  if (key in legacyPrices) {
    return { price: legacyPrices[key], matchedKey: key };
  }
  return null;
}
